telegram_token: "${telegram_bot_token}"
split_msg_byte: 4000
send_only: true
time_outdata: "02/01/2006 15:04:05" # ONLY IF YOU USING DATA FORMATTING FUNCTION
template_path: "template.tmpl" # ONLY IF YOU USING TEMPLATE
time_zone: "${telegram_bot_timezone}" # ONLY IF YOU USING TEMPLATE