{
 "title": "chainlink",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "head_tracker_current_head",
   "type": "stat",
   "description": "The highest seen head number",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "head_tracker_current_head" }
   ]
  },
  {
   "title": "head_tracker_heads_received",
   "type": "stat",
   "description": "The total number of heads seen",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "head_tracker_heads_received" }
   ]
  },
  {
   "title": "head_tracker_num_heads_dropped",
   "type": "stat",
   "description": "The total number of heads dropped",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "head_tracker_num_heads_dropped" }
   ]
  },
  {
   "title": "job_subscriber_subscriptions",
   "type": "stat",
   "description": "The number of job subscriptions currently active",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "job_subscriber_subscriptions" }
   ]
  },
  {
   "title": "tx_manager_gas_bump_underpriced_replacement",
   "type": "stat",
   "description": "Number of underpriced replacement errors received while trying to bump gas. Counts of this type most likely indicate some kind of misconfiguration or problem.",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tx_manager_gas_bump_underpriced_replacement"
    }
   ]
  },
  {
   "title": "tx_manager_gas_bump_exceeds_limit",
   "type": "stat",
   "description": "Number of times gas bumping failed from exceeding the configured limit. Any counts of this type indicate a serious problem.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tx_manager_gas_bump_exceeds_limit"
    }
   ]
  },
  {
   "title": "head_tracker_heads_in_queue",
   "type": "timeseries",
   "description": "The number of heads currently waiting to be executed. You can think of this as the 'load' on the head tracker. Should rarely or never be more than 0",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 3 },
   "targets": [
    { "expr": "head_tracker_heads_in_queue" }
   ]
  },
  {
   "title": "tx_manager_num_gas_bumps",
   "type": "timeseries",
   "description": "Number of gas bumps",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 5 },
   "targets": [
    { "expr": "tx_manager_num_gas_bumps" }
   ]
  },
  {
   "title": "tx_manager_tx_attempt_failed",
   "type": "stat",
   "description": "Number of tx attempts that failed. Tx attempts should not fail in normal operation.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tx_manager_tx_attempt_failed" }
   ]
  },
  {
   "title": "run_status_update_total{status=\"errored\"}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "run_status_update_total{status=\"errored\"}"
    }
   ]
  },
  {
   "title": "run_status_update_total{status=\"completed\"}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "run_status_update_total{status=\"completed\"}"
    }
   ]
  },
  {
   "title": "eth balance",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "eth_balance" }
   ]
  },
  {
   "title": "gas_updater_all_gas_percetiles",
   "type": "graph",
   "gridPos": { "h": 14, "w": 9, "x": 15, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gas_updater_all_gas_percetiles" }
   ]
  },
  {
   "title": "adapter_perform_complete_total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "adapter_perform_complete_total" }
   ]
  },
  {
   "title": "service_gonic_requests_total",
   "type": "timeseries",
   "description": "How many HTTP requests processed, partitioned by status code and HTTP method.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "service_gonic_requests_total" }
   ]
  }
 ]
}